extern const int mask_nch_tbl[64] = 
{
  0, 1, 1, 2, 1, 2, 2, 3, 
  1, 2, 2, 3, 2, 3, 3, 4, 
  1, 2, 2, 3, 2, 3, 3, 4, 
  2, 3, 3, 4, 3, 4, 4, 5, 
  1, 2, 2, 3, 2, 3, 3, 4, 
  2, 3, 3, 4, 3, 4, 4, 5, 
  2, 3, 3, 4, 3, 4, 4, 5, 
  3, 4, 4, 5, 4, 5, 5, 6, 
};

extern const int mask_order_tbl[64][6] =
{
  {  },
  { CH_L },
  { CH_C },
  { CH_L, CH_C },
  { CH_R },
  { CH_L, CH_R },
  { CH_C, CH_R },
  { CH_L, CH_C, CH_R },
  { CH_SL },
  { CH_L, CH_SL },
  { CH_C, CH_SL },
  { CH_L, CH_C, CH_SL },
  { CH_R, CH_SL },
  { CH_L, CH_R, CH_SL },
  { CH_C, CH_R, CH_SL },
  { CH_L, CH_C, CH_R, CH_SL },
  { CH_SR },
  { CH_L, CH_SR },
  { CH_C, CH_SR },
  { CH_L, CH_C, CH_SR },
  { CH_R, CH_SR },
  { CH_L, CH_R, CH_SR },
  { CH_C, CH_R, CH_SR },
  { CH_L, CH_C, CH_R, CH_SR },
  { CH_SL, CH_SR },
  { CH_L, CH_SL, CH_SR },
  { CH_C, CH_SL, CH_SR },
  { CH_L, CH_C, CH_SL, CH_SR },
  { CH_R, CH_SL, CH_SR },
  { CH_L, CH_R, CH_SL, CH_SR },
  { CH_C, CH_R, CH_SL, CH_SR },
  { CH_L, CH_C, CH_R, CH_SL, CH_SR },
  { CH_LFE },
  { CH_L, CH_LFE },
  { CH_C, CH_LFE },
  { CH_L, CH_C, CH_LFE },
  { CH_R, CH_LFE },
  { CH_L, CH_R, CH_LFE },
  { CH_C, CH_R, CH_LFE },
  { CH_L, CH_C, CH_R, CH_LFE },
  { CH_SL, CH_LFE },
  { CH_L, CH_SL, CH_LFE },
  { CH_C, CH_SL, CH_LFE },
  { CH_L, CH_C, CH_SL, CH_LFE },
  { CH_R, CH_SL, CH_LFE },
  { CH_L, CH_R, CH_SL, CH_LFE },
  { CH_C, CH_R, CH_SL, CH_LFE },
  { CH_L, CH_C, CH_R, CH_SL, CH_LFE },
  { CH_SR, CH_LFE },
  { CH_L, CH_SR, CH_LFE },
  { CH_C, CH_SR, CH_LFE },
  { CH_L, CH_C, CH_SR, CH_LFE },
  { CH_R, CH_SR, CH_LFE },
  { CH_L, CH_R, CH_SR, CH_LFE },
  { CH_C, CH_R, CH_SR, CH_LFE },
  { CH_L, CH_C, CH_R, CH_SR, CH_LFE },
  { CH_SL, CH_SR, CH_LFE },
  { CH_L, CH_SL, CH_SR, CH_LFE },
  { CH_C, CH_SL, CH_SR, CH_LFE },
  { CH_L, CH_C, CH_SL, CH_SR, CH_LFE },
  { CH_R, CH_SL, CH_SR, CH_LFE },
  { CH_L, CH_R, CH_SL, CH_SR, CH_LFE },
  { CH_C, CH_R, CH_SL, CH_SR, CH_LFE },
  { CH_L, CH_C, CH_R, CH_SL, CH_SR, CH_LFE },
};
